apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gordion-relay-hpa
  namespace: gordion-relay
  labels:
    app: gordion-relay
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gordion-relay
  minReplicas: 1
  maxReplicas: 3  # Limited due to QUIC connection affinity requirements
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60