apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gordion-relay-pdb
  namespace: gordion-relay
  labels:
    app: gordion-relay
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gordion-relay