apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gordion-relay-certs
  namespace: gordion-relay
  labels:
    app: gordion-relay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  # Uncomment and adjust for your cluster
  # Common values: standard, nfs-client, local-path, vsphere-storage