apiVersion: v1
kind: Service
metadata:
  name: gordion-relay-service
  namespace: gordion-relay
  labels:
    app: gordion-relay
  annotations:
    # Cloud provider specific annotations
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # AWS Network Load Balancer for UDP
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "zenpacs-rg"  # Azure
    cloud.google.com/load-balancer-type: "External"  # GCP
    # Preserve source IP for rate limiting
    service.beta.kubernetes.io/external-traffic: "OnlyLocal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Preserve source IP for rate limiting
  sessionAffinity: ClientIP  # Important for QUIC connection persistence
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour session affinity
  selector:
    app: gordion-relay
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: quic
    port: 443
    targetPort: 443
    protocol: UDP  # Critical: QUIC is UDP only
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
---
# Internal service for metrics scraping
apiVersion: v1
kind: Service
metadata:
  name: gordion-relay-metrics
  namespace: gordion-relay
  labels:
    app: gordion-relay
    service-type: metrics
spec:
  type: ClusterIP
  selector:
    app: gordion-relay
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP