apiVersion: v1
kind: Service
metadata:
  name: gordion-relay-service
  namespace: gordion-relay
  labels:
    app: gordion-relay
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  selector:
    app: gordion-relay
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
# Internal service for metrics scraping
apiVersion: v1
kind: Service
metadata:
  name: gordion-relay-metrics
  namespace: gordion-relay
  labels:
    app: gordion-relay
    service-type: metrics
spec:
  type: ClusterIP
  selector:
    app: gordion-relay
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP