apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gordion-relay-metrics
  namespace: gordion-relay
  labels:
    app: gordion-relay
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: gordion-relay
      service-type: metrics
  endpoints:
  - port: metrics
    interval: 30s
    path: /status
    scheme: http
    honorLabels: true
  namespaceSelector:
    matchNames:
    - gordion-relay