apiVersion: apps/v1
kind: Deployment
metadata:
  name: gordion-relay
  namespace: default
  labels:
    app: gordion-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gordion-relay
  template:
    metadata:
      labels:
        app: gordion-relay
    spec:
      containers:
      - name: relay
        image: gordion-relay:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 8080
          name: metrics
        env:
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: config
          mountPath: /root/config.json
          subPath: config.json
          readOnly: true
        - name: certs
          mountPath: /root/certs
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: gordion-relay-config
      - name: certs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: gordion-relay-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gordion-relay
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: quic
    port: 443
    targetPort: 443
    protocol: UDP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gordion-relay-config
  namespace: default
data:
  config.json: |
    {
      "listen_addr": ":443",
      "domain": "zenpacs.com.tr",
      "tls": {
        "auto_cert": true
      },
      "idle_timeout": "30s",
      "max_concurrent_conn": 1000,
      "request_timeout": "30s",
      "metrics_addr": ":8080"
    }